r"""Fundamental-domain mesh for the three-cone spherical orbifolds ``(p,q,r)``.

The dihedral ``(k,2,2)`` domain is a lune (``spherical_base_mesh``); the platonic
orbifolds -- ``(2,3,3)`` tetrahedral, ``(2,3,4)`` octahedral, ``(2,3,5)`` icosahedral --
have a **kite** fundamental domain instead. The reference constructs it in
``three_point_tile.m``: cut the sphere along a path through the three cone points; the
opened disk is a spherical quadrilateral whose corners are cone 1, the TWO copies of
cone 2 (the cut passes through it, so it appears on both sides), and cone 3:

- corner positions from the angle-angle-angle spherical triangle solve (``aaa.m``) with
  HALF cone angles :math:`\pi/p_i` -- the kite is two mirror triangles glued along the
  cone1-cone3 diagonal;
- cone 1 at the north pole, cone 3 below it on the ``y z`` plane, the cone-2 copies
  symmetric about that plane at azimuth :math:`\pm\pi/p_1`.

The mesh here is those two spherical triangles, barycentrically subdivided and glued
along the diagonal, with structured boundary chains: ``left1`` (cone1 -> cone2a) and
``left2`` (cone2a -> cone3) are the free side of the cut; ``right1``/``right2`` are
their twins, generated by the cone rotations (about cone 1 by :math:`2\pi/p_1`, about
cone 3 by :math:`2\pi/p_3`).
"""

from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from escher.geometry.sphere_tiler import expected_group_order, rotation_matrix

__all__ = ["KiteMesh", "three_point_tile", "get_kite_mesh"]


def three_point_tile(cone_orders: tuple[int, int, int]) -> np.ndarray:
    r"""``(4, 3)`` kite corners ``[cone1, cone2a, cone3, cone2b]`` on the unit sphere.

    Port of ``three_point_tile.m`` (with its ``aaa.m`` angle-angle-angle solve): the
    corner triangle uses HALF cone angles because the kite is two mirror triangles, and
    cone 2 is "a hybrid" -- the cut passes through it, so its full angle is split
    between its two copies.
    """
    expected_group_order(cone_orders)  # validates this is a spherical triple
    A, B, C = (np.pi / o for o in cone_orders)

    def side(alpha, beta, gamma):
        return np.arccos(
            np.clip(
                (np.cos(alpha) + np.cos(beta) * np.cos(gamma))
                / (np.sin(beta) * np.sin(gamma)),
                -1.0,
                1.0,
            )
        )

    b = side(B, A, C)  # arc cone1 -> cone3
    c = side(C, A, B)  # arc cone1 -> cone2

    p1 = np.array([0.0, 0.0, 1.0])
    p2 = np.array([0.0, np.sin(b), np.cos(b)])
    ptemp = np.array([0.0, np.sin(c), np.cos(c)])
    p3 = rotation_matrix([0.0, 0.0, 1.0], A) @ ptemp
    p4 = rotation_matrix([0.0, 0.0, 1.0], -A) @ ptemp
    return np.stack([p1, p3, p2, p4])


@dataclass
class KiteMesh:
    """A disk-topology mesh covering one fundamental domain of a ``(p,q,r)`` orbifold.

    Chain index arrays share their endpoint vertices; ``left1``/``right1`` run
    cone1 -> cone2 copy, ``left2``/``right2`` run cone2 copy -> cone3, so
    ``right_i[j]`` is the rotation image of ``left_i[j]`` position-for-position.
    """

    points: np.ndarray  #: ``(n, 3)`` vertices on the unit sphere
    faces: np.ndarray  #: ``(n_faces, 3)``, counter-clockwise seen from outside
    left1: np.ndarray  #: cone1 -> cone2a
    left2: np.ndarray  #: cone2a -> cone3
    right1: np.ndarray  #: cone1 -> cone2b (twin of left1)
    right2: np.ndarray  #: cone2b -> cone3 (twin of left2)
    cone1: int
    cone2a: int
    cone2b: int
    cone3: int
    uv: np.ndarray
    cone_orders: tuple[int, int, int] = (2, 3, 4)
    metadata: dict = field(default_factory=dict)

    @property
    def n_verts(self) -> int:
        return len(self.points)

    @property
    def edges(self) -> np.ndarray:
        """``(n_edges, 2)`` unique undirected edges with ``i < j``."""
        e = np.concatenate(
            [self.faces[:, [0, 1]], self.faces[:, [1, 2]], self.faces[:, [2, 0]]]
        )
        e = np.sort(e, axis=1)
        return np.unique(e, axis=0)

    @property
    def boundary_chains(self) -> list[np.ndarray]:
        return [self.left1, self.left2, self.right2, self.right1]


def _orient_outward(points: np.ndarray, faces: np.ndarray) -> np.ndarray:
    tri = points[faces]
    normals = np.cross(tri[:, 1] - tri[:, 0], tri[:, 2] - tri[:, 0])
    centroids = tri.mean(axis=1)
    flip = np.einsum("ij,ij->i", normals, centroids) < 0
    faces = faces.copy()
    faces[flip] = faces[flip][:, [0, 2, 1]]
    return faces


def get_kite_mesh(cone_orders: tuple[int, int, int] = (2, 3, 4), n: int = 14) -> KiteMesh:
    r"""Mesh the ``(p,q,r)`` kite as two glued barycentric triangle grids.

    Args:
        cone_orders: the three cone orders; must be a spherical triple.
        n: subdivision level per triangle edge (each chain has ``n + 1`` vertices).

    Vertices are normalized barycentric combinations of the corner directions, which
    samples each triangle smoothly and puts chain vertices on the great-circle arcs
    between corners.
    """
    if n < 2:
        raise ValueError(f"n must be at least 2, got {n}")
    corners = three_point_tile(cone_orders)
    c1, c2a, c3, c2b = corners

    index: dict[tuple[int, int, int], int] = {}
    points: list[np.ndarray] = []
    bary: dict[int, tuple[int, float, float, float]] = {}  # global -> (tri, wA, wB, wC)

    def gkey(tri: int, i: int, j: int) -> tuple[int, int, int]:
        # The diagonal cone1 -> cone3 is shared: tri 0's AC edge (j == i) IS tri 1's
        # AB edge (j == 0), point for point.
        return (0, i, i) if (tri == 1 and j == 0) else (tri, i, j)

    def vertex(tri: int, i: int, j: int, a, b_, c_) -> int:
        key = gkey(tri, i, j)
        if key not in index:
            wa, wb, wc = (n - i) / n, (i - j) / n, j / n
            p = wa * a + wb * b_ + wc * c_
            index[key] = len(points)
            points.append(p / np.linalg.norm(p))
            bary[index[key]] = (tri, wa, wb, wc)
        return index[key]

    faces = []
    tri_corners = [(c1, c2a, c3), (c1, c3, c2b)]
    for tri, (a, b_, c_) in enumerate(tri_corners):
        for i in range(n):
            for j in range(i + 1):
                v00 = vertex(tri, i, j, a, b_, c_)
                v10 = vertex(tri, i + 1, j, a, b_, c_)
                v11 = vertex(tri, i + 1, j + 1, a, b_, c_)
                faces.append([v00, v10, v11])
                if j < i:
                    v01 = vertex(tri, i, j + 1, a, b_, c_)
                    faces.append([v00, v11, v01])
    points_arr = np.stack(points)
    faces_arr = np.asarray(faces, dtype=np.int64)

    left1 = np.array([index[gkey(0, i, 0)] for i in range(n + 1)])  # c1 -> c2a
    left2 = np.array([index[gkey(0, n, j)] for j in range(n + 1)])  # c2a -> c3
    right1 = np.array([index[gkey(1, i, i)] for i in range(n + 1)])  # c1 -> c2b
    # tri 1's B->C edge runs c3 -> c2b; the twin of left2 runs c2b -> c3, so reverse.
    right2 = np.array([index[gkey(1, n, j)] for j in range(n + 1)])[::-1]

    # UV: planar kite preserving the corner angle at cone1 and the two cut arc lengths,
    # same barycentric weights as the sphere -- bijective because the kite is convex.
    A = np.pi / cone_orders[0]
    b_len = np.arccos(np.clip(c1 @ c3, -1, 1))
    c_len = np.arccos(np.clip(c1 @ c2a, -1, 1))
    flat = {
        "c1": np.array([0.0, 0.0]),
        "c3": np.array([0.0, -b_len]),
        "c2a": c_len * np.array([-np.sin(A), -np.cos(A)]),
        "c2b": c_len * np.array([np.sin(A), -np.cos(A)]),
    }
    flat_tris = [
        (flat["c1"], flat["c2a"], flat["c3"]),
        (flat["c1"], flat["c3"], flat["c2b"]),
    ]
    uv = np.zeros((len(points_arr), 2))
    for g, (tri, wa, wb, wc) in bary.items():
        fa, fb, fc = flat_tris[tri]
        uv[g] = wa * fa + wb * fb + wc * fc
    lo, hi = uv.min(axis=0), uv.max(axis=0)
    uv = 0.05 + 0.9 * (uv - lo) / np.maximum(hi - lo, 1e-12)

    return KiteMesh(
        points=points_arr,
        faces=_orient_outward(points_arr, faces_arr),
        left1=left1,
        left2=left2,
        right1=right1,
        right2=right2,
        cone1=index[gkey(0, 0, 0)],
        cone2a=index[gkey(0, n, 0)],
        cone3=index[gkey(0, n, n)],
        cone2b=index[gkey(1, n, n)],
        uv=uv,
        cone_orders=tuple(int(o) for o in cone_orders),
        metadata={"n": n, "corners": corners},
    )
